# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160908_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepref',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tmdb.Movie'),
        ),
        migrations.AlterField(
            model_name='preflist',
            name='movies',
            field=models.ManyToManyField(related_name='preflist', through='accounts.MoviePref', to='tmdb.Movie'),
        ),
    ]
