# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mean_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='moviepref',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tmdb.Movie'),
        ),
    ]
