# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160915_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='preflist',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
