# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_preflist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preflist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preflist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pref', to=settings.AUTH_USER_MODEL),
        ),
    ]
