# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160925_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preflist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref', to=settings.AUTH_USER_MODEL),
        ),
    ]
