# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160926_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepref',
            name='rating',
            field=models.FloatField(),
        ),
    ]
