# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0004_movie_update_level'),
        ('accounts', '0013_profile_watchlistlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(related_name='_watchlist_movies_+', to='tmdb.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlistlist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='watchlistlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='WatchlistList',
        ),
    ]
