# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MoviePopularQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 9, 2, 18, 34, 56, 352781, tzinfo=utc))),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_results', models.IntegerField(blank=True, null=True)),
                ('movies', models.ManyToManyField(to='tmdb.Movie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moviepopularquery',
            unique_together=set([('page',)]),
        ),
    ]
