# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('tmdb_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('tmdb_id',)]),
        ),
    ]
