# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePopularQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('movies', models.ManyToManyField(to='tmdb.Movie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moviepopularquery',
            unique_together=set([('page',)]),
        ),
    ]
