# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepopularquery',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
