# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20160822_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepopularquery',
            name='total_pages',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
