# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20160907_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
