# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0003_auto_20161001_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='update_level',
            field=models.IntegerField(default=0),
        ),
    ]
