# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0003_moviepopularquery_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepopularquery',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
