# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0006_auto_20161020_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='popularquery',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='popularquery',
            name='movies',
        ),
        migrations.DeleteModel(
            name='PopularQuery',
        ),
    ]
