# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0007_auto_20161020_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_results', models.IntegerField(blank=True, null=True)),
                ('movies', models.ManyToManyField(related_name='_upcomingquery_movies_+', to='tmdb.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='upcomingquery',
            unique_together=set([('page',)]),
        ),
    ]
