# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0011_auto_20161030_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
