# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0012_auto_20161030_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
