# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20160907_2033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reco', '0003_auto_20160907_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='reco',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reco',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reco',
            name='base',
            field=models.ManyToManyField(related_name='pref', through='reco.RecoBase', to='tmdb.Movie'),
        ),
        migrations.AddField(
            model_name='recomovie',
            name='reco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Reco'),
        ),
        migrations.AddField(
            model_name='reco',
            name='movies',
            field=models.ManyToManyField(through='reco.RecoMovie', to='tmdb.Movie'),
        ),
    ]
