# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20160907_2033'),
        ('reco', '0006_auto_20160907_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tmdb.Movie')),
                ('sim_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tmdb.Movie')),
            ],
        ),
    ]
