# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0007_moviesim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesim',
            name='base_movie',
        ),
        migrations.RemoveField(
            model_name='moviesim',
            name='sim_movie',
        ),
        migrations.DeleteModel(
            name='MovieSim',
        ),
    ]
