# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0010_reco_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recobase',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tmdb.Movie'),
        ),
        migrations.AlterField(
            model_name='recobase',
            name='reco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reco.Reco'),
        ),
        migrations.AlterField(
            model_name='recomovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tmdb.Movie'),
        ),
        migrations.AlterField(
            model_name='recomovie',
            name='reco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data2', to='reco.Reco'),
        ),
    ]
