# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0011_auto_20161015_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reco',
            name='base',
        ),
        migrations.RemoveField(
            model_name='reco',
            name='movies',
        ),
        migrations.AlterField(
            model_name='recobase',
            name='reco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='reco.Reco'),
        ),
        migrations.AlterField(
            model_name='recomovie',
            name='reco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='reco.Reco'),
        ),
    ]
